<?php

return array(
	'title'      => esc_html__( 'Single Post Settings', 'acuasafe' ),
	'id'         => 'single_post_setting',
	'desc'       => '',
	'subsection' => true,
	'fields'     => array(
		array(
			'id'      => 'single_source_type',
			'type'    => 'button_set',
			'title'   => esc_html__( 'Single Post Source Type', 'acuasafe' ),
			'options' => array(
				'd' => esc_html__( 'Default', 'acuasafe' ),
				'e' => esc_html__( 'Elementor', 'acuasafe' ),
			),
			'default' => 'd',
		),
		array(
			'id'      => 'single_post_cat',
			'type'    => 'switch',
			'title'   => esc_html__( 'Show Category', 'acuasafe' ),
			'desc'    => esc_html__( 'Enable to show post category on posts single page', 'acuasafe' ),
			'default' => true,
		),
		array(
			'id'      => 'single_post_author',
			'type'    => 'switch',
			'title'   => esc_html__( 'Show Author', 'acuasafe' ),
			'desc'    => esc_html__( 'Enable to show author on posts detail page', 'acuasafe' ),
			'default' => true,
		),
		array(
			'id'      => 'single_post_date',
			'type'    => 'switch',
			'title'   => esc_html__( 'Show Date', 'acuasafe' ),
			'desc'    => esc_html__( 'Enable to show post publish date on posts detail page', 'acuasafe' ),
			'default' => true,
		),
		array(
			'id'      => 'single_post_share',
			'type'    => 'switch',
			'title'   => esc_html__( 'Show Social Share', 'acuasafe' ),
			'desc'    => esc_html__( 'Enable to show social Share options', 'acuasafe' ),
			'default' => false,
		),
		array(
			'id'       => 'single_social_share',
			'type'     => 'sortable',
			'title'    => esc_html__( 'Post Sharing Icons', 'acuasafe' ),
			'subtitle' => esc_html__( 'Select icons to activate social sharing icons in post detail page', 'acuasafe' ),
			'required' => array( 'blog_post_share', '=', true ),
			'mode'     => 'checkbox',
			'required' => array( 'single_post_share', '=', true ),
			'options'  => array(
				'facebook'    => esc_html__( 'Facebook', 'acuasafe' ),
				'twitter'     => esc_html__( 'Twitter', 'acuasafe' ),
				'gplus'       => esc_html__( 'Google Plus', 'acuasafe' ),
				'digg'        => esc_html__( 'Digg Digg', 'acuasafe' ),
				'reddit'      => esc_html__( 'Reddit', 'acuasafe' ),
				'linkedin'    => esc_html__( 'Linkedin', 'acuasafe' ),
				'pinterest'   => esc_html__( 'Pinterest', 'acuasafe' ),
				'stumbleupon' => esc_html__( 'Sumbleupon', 'acuasafe' ),
				'tumblr'      => esc_html__( 'Tumblr', 'acuasafe' ),
				'email'       => esc_html__( 'Email', 'acuasafe' ),
			),
		),
		array(
			'id'       => 'single_default_st',
			'type'     => 'section',
			'title'    => esc_html__( 'Post Default', 'acuasafe' ),
			'indent'   => true,
			'required' => [ 'single_source_type', '=', 'd' ],
		),
		array(
			'id'       => 'single_section_default_ed',
			'type'     => 'section',
			'indent'   => false,
			'required' => [ 'single_source_type', '=', 'd' ],
		),
	),
);